---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns
spec:

  template:

    spec:

      containers:

        - name: dns

          ports:
            - containerPort: 853
              name: dns-over-tls
              protocol: TCP
