---
apiVersion: v1
kind: Service
metadata:
  name: centurion-ui
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: centurion-ui
spec:
  selector:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: centurion-ui
  ports:
    - name: ui
      port: 80
      targetPort: ui
