---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: nginx
  name: nginx
data:
  # yamllint disable rule:indentation
  default.conf: |
    server {

        listen 80;

        access_log /var/log/nginx/access-default.log main;
        error_log /var/log/nginx/error-default.log;

        error_page   500 502 503 504  /50x.html;

            location /  {
              root    /usr/share/nginx/html/;

            }
    }
  # yamllint enable rule:indentation
