---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: website


commonLabels:
  app.kubernetes.io/instance: cluster
  app.kubernetes.io/name: nginx
  app.kubernetes.io/part-of: nginx


resources:
  - configmap-nginx.yaml
  - service.yaml
  - deployment-nginx.yaml
