---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base


components:
  - ../../components/metrics


patches:
  #
  # Add to Top-most Kustomization.yaml
  #
  # yamllint disable rule:indentation
  - patch: |-

      - op: replace
        path: /spec/imageName
        value: ghcr.io/cloudnative-pg/postgresql:15.12-11
      # yamllint enable rule:indentation
    target:
      kind: Cluster
