---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics

resources:
  - ../../base

components:
  - ../../components/metrics
  - ../../components/mixin-prometheusrule
  - ../../components/networkpolicy
