---

- name: Update Application Variables
  hosts: localhost
  gather_facts: false
  connection: local


  pre_tasks:


    - name: Get current GIT branch
      ansible.builtin.command:
        cmd: git branch --show-current
      changed_when: false
      register: get_git_branch_current


    - name: Play Facts
      ansible.builtin.set_fact:
        # yamllint disable rule:indentation
        # noqa: jinja[spacing]
        repo_root: |-
          {{ lookup( 'ansible.builtin.env', 'GITHUB_WORKSPACE') | default(
              lookup('ansible.builtin.env', 'PWD'), true) }}
        # yamllint enable rule:indentation
        git_branch_current: "{{ get_git_branch_current.stdout | trim }}"
        github_pull_request_assignee_users: |-
          {{ lookup( 'ansible.builtin.env', 'PR_ASSIGNEE_USERS') | default(omit) }}


  tasks:


    - name: Run Versions update
      ansible.builtin.include_role:
        name: app-versions


  post_tasks:


    - name: Commit any changes
      ansible.builtin.include_role:    # noqa: no-handler
        name: git
      vars:
        git_commit_exclude: []
        git_commit_path: "{{ playbook_dir }}/../vars/versions.yaml"
        git_commit_message: "chore: Updated Application Versions"


    - name: Create PR
      ansible.builtin.include_role:    # noqa: no-handler
        name: github
        tasks_from: pull-request
      vars:
        github_branch_working: "{{ git_branch_working | string }}"
        github_assign_pull_request: true
        github_pull_request_title: "chore: Updated Application Versions"
      when: git_commit_create.changed | default(false)
