---

- name: Update Kustomize manifests directory
  hosts: localhost
  gather_facts: false
  connection: local


  pre_tasks:

    - name: Get current GIT branch
      ansible.builtin.command:
        cmd: git branch --show-current
      changed_when: false
      register: get_git_branch_current


    - name: Play Facts
      ansible.builtin.set_fact:
        # yamllint disable rule:indentation
        # noqa: jinja[spacing]
        repo_root: |-
          {{ lookup( 'ansible.builtin.env', 'GITHUB_WORKSPACE') | default(
              lookup('ansible.builtin.env', 'PWD'), true) }}
        # yamllint enable rule:indentation
        git_branch_current: "{{ get_git_branch_current.stdout | trim }}"
        github_pull_request_assignee_users: |-
          {{ lookup( 'ansible.builtin.env', 'PR_ASSIGNEE_USERS') | default(omit) }}


    - name: Load Application Variables
      ansible.builtin.include_vars:
        file: "../vars/applications.yaml"


    - name: Load Versions Variables
      ansible.builtin.include_vars:
        file: "../vars/versions.yaml"


    - name: Fetch Manifest Directories
      ansible.builtin.find:
        paths: "{{ repo_root }}/manifests"
        file_type: directory
        recurse: false
      register: manifest_directories


  tasks:


    - name: Run manifest tasks
      ansible.builtin.include_role:
        name: kustomize-manifest-update
      loop: "{{ manifest_directories.files }}"
      loop_control:
        loop_var: manifest_directory
      vars:
        directory_manifest: "manifests"
        directory_application: "{{ manifest_directory.path | basename }}"


  post_tasks:


    - name: Create PR
      ansible.builtin.include_role:    # noqa: no-handler
        name: github
        tasks_from: pull-request
      vars:
        github_branch_working: "{{ git_branch_working | string }}"
        github_assign_pull_request: true
        github_pull_request_title: "build: Update Templated Manifests"
      when: has_commits | default(false)
