---

- name: Load Application Variables
  ansible.builtin.include_vars:
    file: "../vars/applications.yaml"


- name: Load Versions Variables
  ansible.builtin.include_vars:
    file: "../vars/versions.yaml"


- name: Check for Application Updates
  ansible.builtin.include_tasks:
    file: fetch-version-details.yaml
  loop: "{{ applications }}"
  loop_control:
    loop_var: application
  when: >
    directory_application | default('') == ''


- name: Check for Updates for {{ directory_application }}
  ansible.builtin.include_tasks:
    file: fetch-version-details.yaml
  loop: "{{ applications }}"
  loop_control:
    loop_var: application
  when: >
    directory_application | default('') != ''
      and
    directory_application | default('') == application.repository.name


- name: Trace, Show Versions
  ansible.builtin.debug:
    msg: "{{ dict(versions | dictsort) }}"


- name: Write config
  ansible.builtin.copy:
    # yamllint disable rule:indentation
    # noqa: jinja[spacing]
    content: |
      ---

      #
      # Do not edit this file manually as its auto-created by role app-versions.
      #

      {{ { "versions": dict(versions | dictsort) } | to_nice_yaml( indent = 2 ) }}

    # yamllint enable rule:indentation
    dest: "{{ playbook_dir }}/../vars/versions.yaml"
    mode: "0644"
