---

- name: Check if GIT working branch exists
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git show-ref --verify --quiet  refs/remotes/origin/{{ git_branch_working }}
  changed_when: git_branch_exists.rc == 0
  failed_when: >    # 0 = Exists, 1 = Not exist.
    git_branch_exists.rc > 1
  register: git_branch_exists


- name: Check if GIT working branch exists locally
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git show-ref --verify --quiet  refs/heads/{{ git_branch_working }}
  changed_when: false
  failed_when: >    # 0 = Exists, 1 = Not exist.
    git_branch_exists_locally.rc > 1
  register: git_branch_exists_locally


- name: Git stash changes
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git stash push --include-untracked -m create-branch
  # yamllint disable rule:indentation
  changed_when: >-
    git_stash.rc == 0
      and
    'No local changes to save' not in git_stash.stdout
  # yamllint disable rule:indentation
  register: git_stash


- name: Create GIT working branch
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git switch -c {{ git_branch_working }} origin/development
  changed_when: git_commit_changes.rc == 0
  register: git_commit_changes
  # yamllint disable rule:indentation
  when: >-
    not git_branch_exists.changed
  # yamllint enable rule:indentation


- name: Checkout GIT working branch
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git switch --track origin/{{ git_branch_working }}
  changed_when: git_commit_changes.rc == 0
  register: git_commit_changes
  when: >-
    git_branch_exists.changed
      and
    not git_branch_exists_locally.rc == 0


- name: Rebase on development branch
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git pull origin development --rebase
  changed_when: false
  when: >-
    git_branch_exists.changed
      and
    not git_branch_exists_locally.rc == 0


- name: Checkout GIT working branch
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git switch {{ git_branch_working }}
  changed_when: git_commit_changes.rc == 0
  register: git_commit_changes
  when: >-
    git_branch_exists_locally.rc == 0


- name: Pop latest GIT stash
  ansible.builtin.command:    # noqa: command-instead-of-module no-handler
    cmd: git stash pop
  changed_when: git_stash_pop.rc == 0
  register: git_stash_pop
  when: >-
    git_stash.changed
