---

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: namespace
      app.kubernetes.io/name: grafana-operator
      app.kubernetes.io/part-of: grafana-operator


resources:
  - service.yaml
  - servicemonitor.yaml
