---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: grafana-operator-controller-manager
spec:
  endpoints:
    - interval: 30s
      port: metrics
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
