---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: grafana-operator-controller-manager-metrics
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
    - name: pprof
      port: 8888
      protocol: TCP
      targetPort: pprof
  selector:
    app.kubernetes.io/component: controller
  type: ClusterIP
