---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
  name: prometheus
spec:
  endpoints:
    - interval: 30s
      port: web
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: instance
        - targetLabel: "job"
          replacement: "prometheus"
    - interval: 30s
      port: reloader-web
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
