---

apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  labels:
    app.kubernetes.io/component: message-queuing
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: centurion-erp
  name: vhost-centurion
spec:
  name: centurion
  rabbitmqClusterReference:
    name: main
    namespace: rabbitmq
