---
#
# tag: 1.31.0
# commit: e8254fb99328edd9e78f6646e8abc2f7a42fdd96
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namePrefix: gitlab-runner-


labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: ci-cd-runner
      app.kubernetes.io/name: gitlab
      app.kubernetes.io/part-of: gitlab-runner-operator


# crds:
#   # config/default/kustomization.yaml
#   # - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator//config/crd?ref=e8254fb99328edd9e78f6646e8abc2f7a42fdd96
#   - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/-/raw/e8254fb99328edd9e78f6646e8abc2f7a42fdd96/config/crd/bases/apps.gitlab.com_runners.yaml


images:
  # image details fetched from https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/-/releases using file `operator.k8s.yaml`
  # config/manager/kustomization.tpl.yaml
  - name: controller
    newName: |-
      registry.gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/gitlab-runner-operator
    newTag: "v1.31.0"
    # config/manager/kustomization.tpl.yaml
  - name: kube-rbac-proxy
    newName: |-
      "registry.gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/openshift4/ose-kube-rbac-proxy"
    newTag: "v4.13.0"


resources:
    # Dont use default as it points to invalid kustomize dirs
  # - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator//config/default?ref=e8254fb99328edd9e78f6646e8abc2f7a42fdd96

    # config/default/kustomization.yaml
  - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator//config/crd?ref=e8254fb99328edd9e78f6646e8abc2f7a42fdd96

    # config/default/kustomization.yaml
  - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator//config/rbac?ref=e8254fb99328edd9e78f6646e8abc2f7a42fdd96

    # config/manager/kustomization.tpl.yaml
  # - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator//config/manager/manager.yaml?ref=e8254fb99328edd9e78f6646e8abc2f7a42fdd96
  - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/-/raw/29031ec8946ebb30e73834d2a34812a47a1d3996/config/manager/manager.yaml


components:
  # config/manager/kustomization.tpl.yaml
  - https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator//config/manager/components/kubernetes?ref=e8254fb99328edd9e78f6646e8abc2f7a42fdd96


patches:
  # config/manager/kustomization.tpl.yaml
  - path: |-
      https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/-/raw/e8254fb99328edd9e78f6646e8abc2f7a42fdd96/config/manager/auth_proxy_patch.yaml

  # Operator only has arch AMD64
  - patch: |-
      - op: replace
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
    target:
      kind: Deployment
      name: controller-manager
      version: v1
