---
apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  labels:
    app.kubernetes.io/component: exporter
spec:
  selector:
    app.kubernetes.io/component: exporter
  ports:
    - name: grafana-metrics
      port: 12345
      targetPort: grafana-metrics
    - name: kube-ctrl-mgr
      port: 11257
      targetPort: kube-ctrl-mgr
  sessionAffinity: ClientIP
