---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: ha
    app.kubernetes.io/instance: production
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: production-ha
  name: main-rw
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: -updated_by_replacement-
    cnpg.io/instanceRole: primary
  sessionAffinity: None
  type: ClusterIP
