---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: ci-cd-runner
  name: gitlab-runner
data:
  # yamllint disable rule:indentation
  config.toml: |
    [[runners]]

      shell = "bash"

      [runners.kubernetes]
        pull_policy = "if-not-present"

        cpu_limit = "1000m"
        cpu_request = "10m"
        helper_cpu_limit = "100m"
        helper_cpu_request = "10m"
        service_cpu_limit = "100m"
        service_cpu_request = "10m"

        memory_limit = "1G"
        memory_request = "64M"
        helper_memory_limit = "256M"
        helper_memory_request = "64M"
        service_memory_limit = "128M"
        service_memory_request = "64M"


        [[runners.kubernetes.volumes.host_path]]
          name = "html"
          mount_path = "/html"
          read_only = false
          host_path = "/opt/webserver/nofusscomputing.com"

        [runners.kubernetes.node_tolerations]
          "CriticalAddonsOnly=true" = "NoExecute"
  # yamllint enable rule:indentation