---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: ci-cd-runner
  name: gitlab-runner
data:
  config.toml: |
    [[runners]]

      shell = "bash"

      [runners.kubernetes]
        namespace = "test"
        helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:alpine-edge-x86_64-latest"
        image = "alpine"
        pull_policy = "if-not-present}"

        cpu_limit = "100m"
        cpu_request = "50m"
        helper_cpu_limit = "100m"
        helper_cpu_request = "50m"
        service_cpu_limit = "100m"
        service_cpu_request = "50m"

        memory_limit = "512M"
        memory_request = "64M"
        helper_memory_limit = "128M"
        helper_memory_request = "64M"
        service_memory_limit = "128M"
        service_memory_request = "64M"


        [[runners.kubernetes.volumes.host_path]]
          name = "html"
          mount_path = "/html"
          read_only = false
          host_path = "/opt/webserver/nofusscomputing.com"

        [runners.kubernetes.node_selector]
          "node-role.kubernetes.io/prime" = "true"

        [runners.kubernetes.node_tolerations]
          "CriticalAddonsOnly=true" = "NoExecute"