---

apiVersion: apps.gitlab.com/v1beta2
kind: Runner
metadata:
  labels:
    app.kubernetes.io/component: ci-cd-runner
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/part-of: nginx
  name: ci
spec:
  config: gitlab-runner
  gitlabUrl: https://gitlab.com
  podSpec:
    - name: gitlab-runner
      patchType: merge
      patch: |
        securityContext:
          runAsNonRoot: false
  token: gitlab-runner-token
