---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# components:
#   - ../../components/ingress

images:
  # This image is intended to be kept up to date with feat-* and dev branch.
  - name: nofusscomputing/centurion-erp-ui
    newName: nofusscomputing/centurion-erp-ui
    newTag: 7c1e90b02efb1d22da1faad1a6ec23ddef8eb03b

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: cluster

  - pairs:
      app.kubernetes.io/version: v1.30.1

namespace: centurion-ui

# patches:
#   - patch: |-

#       - op: replace
#         path: /metadata/annotations/cert-manager.io~1cluster-issuer
#         value: cluster

#       - op: replace
#         path: /metadata/annotations/cert-manager.io~1common-name
#         value: sub-domain.domain.tld

#       - op: replace
#         path: /spec/rules/0/host
#         value: sub-domain.domain.tld

#       - op: replace
#         path: /spec/tls/0/hosts/0
#         value: sub-domain.domain.tld
#     target:
#       kind: Ingress
#       name: centurion-ui
#       version: v1


resources:
  - ../../base
