---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

# components:
#   - ../../components/extra-conf
#   - ../../components/git-ops
#   - ../../components/rndc
#   - ../../components/dns-over-http
#   - ../../components/dns-over-tls

namespace: dns


images:
  - name: nofusscomputing/bind
    newTag: '1.0.0'
