---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: certs


helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: certs
    version: 'v1.16.2'
    additionalValuesFiles:
      - values-custom.yaml
    valuesFile: values-default.yaml
