---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: alerting
  name: cluster
spec:
  ports:
    - name: web
      port: 9093
      targetPort: web
    - name: reloader-web
      port: 8080
      targetPort: reloader-web
  selector:
    app.kubernetes.io/component: alerting
  sessionAffinity: ClientIP
