---

- name: Git Repo information
  block:


    - name: Checkout repository
      ansible.builtin.git:
        repo: "{{ manifest_git_provider }}/{{ manifest_git_repository }}.git"
        dest: "{{ playbook_dir }}/workdir"
        single_branch: yes
        version: "{{ manifest_git_branch }}"
      changed_when: false
      register: git_checkout
      when: manifest_git_provider is defined


    - name: Fetch the latest Git release tag
      ansible.builtin.shell:
        cmd: |
          set -o pipefail;
          git tag --sort=-v:refname | head -n 1
        chdir: "{{ playbook_dir }}/workdir"
        executable: /bin/bash
      changed_when: false
      failed_when: git_tag_latest.stdout_lines | length != 1
      register: git_tag_latest
      when: manifest_git_provider is defined


    - name: Fetch the latest Git release tag sha
      ansible.builtin.shell:
        cmd: |
          set -o pipefail;
          git rev-list -n 1 "$(git tag --sort=-v:refname | head -n 1)"
        chdir: "{{ playbook_dir }}/workdir"
        executable: /bin/bash
      changed_when: false
      failed_when: git_tag_latest_sha.stdout_lines | length != 1
      register: git_tag_latest_sha
      when: manifest_git_provider is defined


    - name: Play Facts
      ansible.builtin.set_fact:
        git_version_head: "{{ git_checkout.after[:8] }}"
        git_version_latest: "{{ git_tag_latest.stdout | trim }}"
        git_sha_version_head: "{{ git_checkout.after }}"
        git_sha_version_latest: "{{ git_tag_latest_sha.stdout | trim }}"


  always:

    - name: Cleanup
      ansible.builtin.command:
        cmd: rm -rf workdir/
      changed_when: false
