---

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

namespace: centurion

secretGenerator:
  - name: social-auth-keycloak
    files:
      - 70.social_auth_keycloak.py

patches:

  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/0/projected/sources/-
        value:
          secret:
            name: social-auth-keycloak

    target:
      kind: Deployment
      name: api
      version: v1
