---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: bind9
    app.kubernetes.io/name: dns
  name: dns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: bind9
      app.kubernetes.io/name: dns
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/component: bind9
        app.kubernetes.io/name: dns
    spec:
      terminationGracePeriodSeconds: 10
      affinity: {}
      containers:

        - name: dns
          image: nofusscomputing/bind:dev
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 100Mi

          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: tcp
            - containerPort: 53
              name: dns-udp
              protocol: udp

          volumeMounts:
            - name: data
              mountPath: /etc/bind/conf.d/external
              subPath: /git/conf/conf.d/external
            - name: data
              mountPath: /etc/bind/conf.d/acl
              subPath: /git/conf/conf.d/acl
            - name: /git/conf/conf.d/internal
              mountPath: /etc/bind/conf.d/internal
              subPath: /git/conf/conf.d/internal

            - name: data
              mountPath: /var/bind/dyn
              subPath: /git/zones/dyn
            - name: data
              mountPath: /var/bind/pri
              subPath: /git/zones/pri
            - name: data
              mountPath: /var/bind/sec
              subPath: /git/zones/sec

            - mountPath: /var/log
              name: data
              subPath: /logs

      priorityClassName: cluster-low
      tolerations: []
      volumes:

        - name: data
          persistentVolumeClaim:
            claimName: bind
