---
apiVersion: v1
kind: Service
metadata:
  name: bind
  labels:
    app.kubernetes.io/name: bind
    app.kubernetes.io/part-of: bind
spec:
  selector:
    app.kubernetes.io/name: bind
    app.kubernetes.io/part-of: bind
  ports:
    - name: tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
