---

name: Mirror


on:
  push:
    branches:
      - '-NO-RUN-'


jobs:


  mirror-github:
    name: Github
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git.nofusscomputing.com:infrastructure/kubernetes.git
          ssh_private_key: ${{ secrets.SSH_DEPLOY_KEY_GITEA }}
          ssh_username: git
