---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns
spec:
  template:

    spec:

      containers:

        - name: git
          image: alpine:3.23.2
          command:
            - sh
            - -c
            - |
              echo "Installing pre-reqs.....";

              apk update;
              apk add git openssh-client-default;

              export KEY_FILE_PATH=~/.ssh/${SSH_REPOSITORY_OWNER}/${SSH_REPOSITORY_NAME};

              mkdir -p "${KEY_FILE_PATH}";

              echo "Env var KEY_FILE_PATH=[${KEY_FILE_PATH}] setup";

              echo ${SSH_PRIVATE_KEY} > ${KEY_FILE_PATH}/deploy;

              chmod 600 ${KEY_FILE_PATH}/deploy;

              export GIT_SSH_COMMAND="ssh -i $KEY_FILE_PATH/deploy";

              ssh-keyscan "${SSH_REPOSITORY_HOST}" >> ~/.ssh/known_hosts

              while :; do

                echo "Loop Start......";

                if [ ! -d /git/source/.git ]; then

                  export REPO_NAME_FULL="${SSH_REPOSITORY_HOST}:${SSH_REPOSITORY_OWNER}/${SSH_REPOSITORY_NAME}.git"

                  echo "Env var REPO_NAME_FULL=[${REPO_NAME_FULL}] setup";

                  echo "Clonning repo";

                  git clone -b master git@${REPO_NAME_FULL} /git/source;

                else

                  echo "********************************************";

                  git status;

                  echo "********************************************";
                  cd /git/source;

                  echo "Checking for repo updates";

                  git fetch -fpvt;

                  echo "Pulling any changes....";

                  git pull --rebase

                fi


                sleep 300

              done;

          env:
            - name: SSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_PRIVATE_KEY
            - name: SSH_REPOSITORY_HOST
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_REPOSITORY_HOST
            - name: SSH_REPOSITORY_OWNER
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_REPOSITORY_OWNER
            - name: SSH_REPOSITORY_NAME
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_REPOSITORY_NAME

          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 150Mi
          volumeMounts:
            - name: data
              mountPath: /git
              subPath: git/
