---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns
spec:
  template:

    spec:

      containers:

        - name: git
          image: alpine:3.23.2
          command:
            - sh
            - -c
            - |
              apk update;
              apk add \
                git \ 
                openssh-client-default;

              KEY_FILE_NAME="~/.ssh/${SSH_REPOSITORY_OWNER}/${SSH_REPOSITORY_NAME}/deploy";

              echo ${SSH_PRIVATE_KEY} > ${SSH_REPOSITORY_NAME};

              chmod 600 ${SSH_REPOSITORY_NAME};

              export GIT_SSH_COMMAND="ssh -i ${KEY_FILE_NAME}";

              while :; do

                if [ -d /git/.git ] then

                  git clone -b master ${SSH_REPOSITORY_HOST}/${SSH_REPOSITORY_OWNER}/${SSH_REPOSITORY_NAME}.git /git;

                else

                  cd /git;

                  git fetch -fpvt;

                  git pull --rebase

                fi

              done;

          env:
            - name: SSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_PRIVATE_KEY
            - name: SSH_REPOSITORY_HOST
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_REPOSITORY_HOST
            - name: SSH_REPOSITORY_OWNER
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_REPOSITORY_OWNER
            - name: SSH_REPOSITORY_NAME
              valueFrom:
                secretKeyRef:
                  name: bind-config
                  key: SSH_REPOSITORY_NAME

          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 150Mi
          volumeMounts:
            - name: data
              mountPath: /git
              subPath: git/
