---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
spec:
  isCA: true
  commonName: cluster.local
  secretName: cluster-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io
